# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 214683713ae259a8c5cfde84b67d1c8012ffd766fe8caf5c631253af9e89e21a67bb140688d3456541e1de76d91b94e72e6f186edf24cf26c9b67d28df66a180
  fyber_api_key: "b07a12df7d52e6c118e5d47d3f9e60135b109a1f"
test:
  secret_key_base: db7d6891711e4149416b93c034ecb52c5b9eb02d907e24b3151a656722af502ea5c010dd6b0cbc703a65f095c764519483b8b4f7076ca1e7faa1d5d79fb248b3
  fyber_api_key: "b07a12df7d52e6c118e5d47d3f9e60135b109a1f"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
